name: Greet from container
description: Using docker container action
inputs:
  who-to-greet: 
    description: 'Who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'The time of hello'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
  - "${{ inputs.who-to-greet }}"

  
